### ISSUE TITLE
compatibility issue with jQuery UI (Combined Library) 1.11.3

### ISSUE THREAD

**Issue by Yustie** [meetselva/attrchange#15]
Hi,

It seems that this plugin is not compatible with jQuery UI (Combined Library) 1.11.3. I get a run time error about `resizable()` in this line:

`$(function () {
    $('#divSelector').attrchange({
        callback: function (e) {
            BuildBox();
        }
    }).resizable();
});`

I dont remember the exact error message as I have rolled back to version 1.11.2. But If I look in the change log of the version 1.11.3: http://jqueryui.com/changelog/1.11.3/

I see the following:

Resizable
    Fixed: Correct width when grid approaches zero (#10590, 0a0db09)
    Fixed: Match on exact node name to support custom elements (#10748, 7ff9b28)

Could this be the cause of the run time error?

**Comment by meetselva** [comment]
Would you be able to post an example where I can look at this issue?

**Comment by Yustie** [comment]
Hi,

I just realized after updating to the latest version, I never updated the script include from: 
..../jquery-ui-1.11.2.min.js to ..../jquery-ui-1.11.3.min.js. I just did and it seems to be working now.

I'm closing this issue for now, but if it happens again, I'll reopen a new one.

Sorry!
