### ISSUE TITLE
listening to changes of div with resize css

### ISSUE THREAD

**Issue by nachikethashu** [meetselva/attrchange#21]
Hi,
     May I know what's wrong in the following code snippet? 
     http://jsfiddle.net/nachikethashu/tr307kcr/3/

```
Basically I have a div with following css:
resize: both;
overflow: auto;
```

   And I'm trying to listen to height changes with following snippet
   $('#test').attrchange({
        callback: function (e) {
               $('#logger').text('height changed to ' + $(this).height());
        }
    });

**Comment by meetselva** [comment]
Looks like it is a bug in Chrome: https://code.google.com/p/chromium/issues/detail?id=293948

The jsfiddle works fine in FF.

However, the plugin has an extension that uses polling to detect attribute change which should work fine in all browsers but note it uses polling to detect,

Polling example: http://jsfiddle.net/zdhsmuu2/

**Comment by nachikethashu** [comment]
Oh someone asked the exact question 2 years before and still it's not fixed!
This is an example of major browsers killing nice features like MutationObserver.. :(
