### ISSUE TITLE
Broken link on your github page

### ISSUE THREAD

**Issue by dakusan** [meetselva/attrchange#24]
Apparently, there is no way to contact you through github, stackoverflow, or email, so I guess the only appropriate way to do so is through this.

On https://meetselva.github.io/attrchange/ the very first link needs to be changed from
    https://github.com/meetselva/attrchange/blob/master/attrchange.js
to
    https://github.com/meetselva/attrchange/blob/master/js/attrchange.js

**Comment by meetselva** [comment]
Apologies, those are my old pages. I created new pages and it can be found in the below URL.

http://meetselva.github.io

Also updated the old page to forward to the new web page.

Thanks for letting me know.
