### ISSUE TITLE
Native prototype version of attrchange

### ISSUE THREAD

**Issue by pat-richter** [meetselva/attrchange#3]
Hi,

maybe you know advertising, that fills the body's background with a custom color. I want to prevent this and attrchange seems to be awesome! The problem is, that it's not available before the document is loaded. But the background is filled with a color before.

Is it possible to build a prototype version or anything, that does not require jQuery, so I can use attrchange earlier?

``` javascript
Element.prototype.meetselva_attrchange = function( callback ) {
    ...
}
```

Then I could use it without jQuery on the body element.

_I know the downsides of prototyping, but don't have any other idea therefore. I'm interested in work with you but I don't get it alone._

Kind regards,
Patrick

**Comment by meetselva** [comment]
Hello Patrick,

I don't think document.ready is your problem. The body tag should be available only after its declaration. See this demo below http://jsbin.com/uqenef/1/edit which shows that attrchange doesn't wait until document ready. You can bind attrchange to any element that is available when it is called. 

If my understanding is incorrect, drop me a test case using http://jsfiddle.net or http://jsbin.com where I can look at? 

Regards,
SK

**Comment by pat-richter** [comment]
Hello again,

wow, I did never even thougt about using jQuery without `<$(document).ready()>`. I've read some posts now and have to thank you for this learning. So, a _prototype version_ is not needed. Thank you.

Unfortunately the advertiser does a double check, if the background is inked with the correct color. So it results in an infinite loop.

Thank you very much for the support and the learning.

Kind regards,
Patrick
