### ISSUE TITLE
Question about licencing

### ISSUE THREAD

**Issue by mudcube** [meetselva/attrchange#4]
I found this useful helper function on StackOverflow a week ago, great work on it :)

My question is, what would you think about licensing this helper as MIT/GPL dual license? This would improve the compatibility of AttrChange with other licences substantially.

**Comment by meetselva** [comment]
Thanks. I will look into the dual license.

Any suggestion or thoughts on the benefits of this change will be appreciated.

**Comment by mudcube** [comment]
Hi Selvakumar, the main reason for dual-licensing with GPL/MIT is it opens the doors up to what applications and frameworks that can use your code. GPL is basically less compatible with other licences.

**Comment by meetselva** [comment]
Licensed under the MIT license. GPL seems more restrictive.

**Comment by mudcube** [comment]
Thank you!
