### ISSUE TITLE
Observe changes of characterData and childList

### ISSUE THREAD

**Issue by ghost** [meetselva/attrchange#6]
Hi,
I modified attrchange to observe changes of characterData and childList. Are you interested to include it to your plugin?

Greetz,
milchmann

**Comment by meetselva** [comment]
Thanks for your interest. I would definitely like to include any improvements.

Could you post the changes so I can take a look?  

Thanks,
SK

**Comment by ghost** [comment]
I'm still testing it. But I'll let you know as soon as I'm sure it is working as desired.
