### ISSUE TITLE
Endless loop

### ISSUE THREAD

**Issue by ceroz** [meetselva/attrchange#7]
else if (isDOMAttrModifiedSupported()) { //Opera
            //Good old Mutation Events but the performance is no good
            //http://hacks.mozilla.org/2012/05/dom-mutationobserver-reacting-to-dom-changes-without-killing-browser-performance/
            return this.on('DOMAttrModified', function(event) {
                if (event.originalEvent) event = event.originalEvent; //jQuery normalization is not required for us 
                event.attributeName = event.attrName; //property names to be consistent with MutationObserver
                event.oldValue = event.prevValue; //property names to be consistent with MutationObserver 
                cfg.callback.call(this, event);
            });
        } 

This function made never ending loop in IE9-10. Is there any way to fix this ?

**Comment by meetselva** [comment]
Ceroz,

Could you post a demo of this issue in a http://jsfiddle.net ?

I have demo page http://meetselva.github.io/attrchange/ which works totally fine in IE 10.

SK

**Comment by ceroz** [comment]
I've wrote this too early. The problem was in my script. Sorry about that and thank you for the best jQuery "listener" script :)

**Comment by meetselva** [comment]
Glad it worked for you.
